import type {Metadata} from "next";
import "./globals.css";
import NavBar from "@/components/NavBar/NavBar";
import {ThemeProvider} from "@/components/ThemeProvider";

import {Gabarito,JetBrains_Mono, Libre_Caslon_Text} from "next/font/google";
import FooterComponent from "@/components/FooterComponent/FooterComponent";

const gabarito = Gabarito({
	variable: "--font-sans"
});

const jetbrains = JetBrains_Mono({
	variable: "--font-mono"
});

const libreCaslon = Libre_Caslon_Text({
	variable: "--font-serif",
	weight: "400",
	subsets: ["latin"]
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app"
};

export default function RootLayout({
	children
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html
			lang='en'
			suppressHydrationWarning
			className={`${gabarito.variable} ${libreCaslon.variable} ${jetbrains.variable} antialiased`}
		>
			<body suppressHydrationWarning>
				<ThemeProvider
					attribute='class'
					defaultTheme='system'
					enableSystem
					disableTransitionOnChange
				>
					<NavBar />
					{children}
					<FooterComponent/>
				</ThemeProvider>
			</body>
		</html>
	);
}
